repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        exclude: migrations/
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        exclude: migrations/
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: migrations/