version: '3.7'

services:
  api:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  redis:
    image: "redis:alpine"
  celery:
    build: .
    command: celery -A news_app worker -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A news_app beat -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

volumes:
  postgres_data: