# Generated by Django 3.1.7 on 2021-04-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
