# Generated by Django 3.1.7 on 2021-04-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210404_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvotes_count',
            new_name='upvotes_amount',
        ),
    ]
